name: Comandos de shell

# on: push
on:
  schedule: 
    - cron:  '0,5,10,15,20,25,30,35,40,45,50,55 * * * *'


jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: echo "Hello world"
        shell: bash

      - name: Display the path
        run: |  
                node --version
                npm --version
                ls -la
                cat /etc/os-release
        shell: bash

  comandos_windows:
   runs-on: windows-latest

   steps:
     - name: PowerShell
       run: Get-Location
       shell: powershell

     - name: bash
       run: pwd
       shell: bash
